;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Ability.Attack.Combo",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.Heavy",DevComment="")
+GameplayTagList=(Tag="Ability.Attack.Light",DevComment="")
+GameplayTagList=(Tag="Ability.Skill.Dash",DevComment="")
+GameplayTagList=(Tag="Combo.Window.Open",DevComment="")
+GameplayTagList=(Tag="Cooldown.BasicAttack",DevComment="")
+GameplayTagList=(Tag="Data.ComboCount",DevComment="")
+GameplayTagList=(Tag="Data.DamageMultiplier",DevComment="")
+GameplayTagList=(Tag="Event.Combat.HitConfirm",DevComment="")
+GameplayTagList=(Tag="Event.Combat.TraceStart",DevComment="")
+GameplayTagList=(Tag="Event.Combat.TraceEnd",DevComment="")
+GameplayTagList=(Tag="Event.Combo.WindowOpen",DevComment="")
+GameplayTagList=(Tag="Event.Combo.WindowClose",DevComment="")
+GameplayTagList=(Tag="Event.Combo.Input",DevComment="")
+GameplayTagList=(Tag="Status.Buff.AttackUp",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Slow",DevComment="")
+GameplayTagList=(Tag="Status.Debuff.Stun",DevComment="")
+GameplayTagList=(Tag="UI.Inventory.Open",DevComment="")

